//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERS.Windows.DocumentClone
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CERSEntities : DbContext
    {
        public CERSEntities()
            : base("name=CERSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Document> Documents { get; set; }
        public DbSet<FacilitySubmittal> FacilitySubmittals { get; set; }
        public DbSet<FacilitySubmittalElement> FacilitySubmittalElements { get; set; }
        public DbSet<FacilitySubmittalElementDocument> FacilitySubmittalElementDocuments { get; set; }
        public DbSet<FacilitySubmittalElementResource> FacilitySubmittalElementResources { get; set; }
        public DbSet<FacilitySubmittalElementResourceDocument> FacilitySubmittalElementResourceDocuments { get; set; }
        public DbSet<vFacilitySubmittalElementDocumentManifest> vFacilitySubmittalElementDocumentManifests { get; set; }
    }
}
