//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERS.Windows.DocumentClone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.FacilitySubmittalElementDocuments = new HashSet<FacilitySubmittalElementDocument>();
        }
    
        public int ID { get; set; }
        public string Location { get; set; }
        public Nullable<int> StorageProviderID { get; set; }
        public Nullable<decimal> SizeInKB { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedByID { get; set; }
        public bool Voided { get; set; }
    
        public virtual ICollection<FacilitySubmittalElementDocument> FacilitySubmittalElementDocuments { get; set; }
    }
}
