//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERS.Windows.DocumentClone
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilitySubmittalElement
    {
        public FacilitySubmittalElement()
        {
            this.Resources = new HashSet<FacilitySubmittalElementResource>();
        }
    
        public int ID { get; set; }
        public int CERSID { get; set; }
        public int SubmittalElementID { get; set; }
        public Nullable<int> FacilitySubmittalID { get; set; }
        public int StatusID { get; set; }
        public int TemplateID { get; set; }
        public int OwningRegulatorID { get; set; }
        public int OwningOrganizationID { get; set; }
        public Nullable<int> LastSubmittalDeltaID { get; set; }
        public System.Guid Key { get; set; }
        public Nullable<System.DateTime> SubmittedDateTime { get; set; }
        public Nullable<System.DateTime> LastDueDateOnSubmittalDate { get; set; }
        public string SubmittedByFirstName { get; set; }
        public string SubmittedByLastName { get; set; }
        public string SubmittedByEmail { get; set; }
        public Nullable<int> SubmittedByID { get; set; }
        public string SubmittedByComments { get; set; }
        public Nullable<System.DateTime> SubmittalActionDateTime { get; set; }
        public string SubmittalActionAgentName { get; set; }
        public string SubmittalActionAgentEmail { get; set; }
        public Nullable<int> SubmittalActionAgentID { get; set; }
        public Nullable<int> SubmittalActionRegulatorID { get; set; }
        public string SubmittalActionComments { get; set; }
        public Nullable<System.Guid> EDTClientKey { get; set; }
        public Nullable<int> CERS1FacilityDataID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedByID { get; set; }
        public bool Voided { get; set; }
        public bool ReplacedBySeeded { get; set; }
        public Nullable<int> SeedingBatchID { get; set; }
        public Nullable<long> AttachmentsTotalSizeKB { get; set; }
        public Nullable<int> FSEIDReplacedDuringSeeding { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual FacilitySubmittal FacilitySubmittal { get; set; }
        public virtual FacilitySubmittalElement FacilitySubmittalElement1 { get; set; }
        public virtual FacilitySubmittalElement ReplacedDuringSeeding { get; set; }
        public virtual ICollection<FacilitySubmittalElementResource> Resources { get; set; }
    }
}
