//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERS.Windows.DocumentClone
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilitySubmittal
    {
        public FacilitySubmittal()
        {
            this.FacilitySubmittalElements = new HashSet<FacilitySubmittalElement>();
        }
    
        public int ID { get; set; }
        public System.DateTime SubmittalDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedByID { get; set; }
        public bool Voided { get; set; }
        public string FacilityRegulatorKey { get; set; }
    
        public virtual ICollection<FacilitySubmittalElement> FacilitySubmittalElements { get; set; }
    }
}
