//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CERS.Windows.DocumentClone
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFacilitySubmittalElementDocumentManifest
    {
        public int CERSID { get; set; }
        public string FacilityName { get; set; }
        public int OrganizationID { get; set; }
        public int FSEID { get; set; }
        public Nullable<int> FacilitySubmittalID { get; set; }
        public int SubmittalElementID { get; set; }
        public string SubmittalElementName { get; set; }
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public int FSERID { get; set; }
        public int FSERDID { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public int FormatID { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public string DocumentTypeName { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> StorageProviderID { get; set; }
        public Nullable<decimal> SizeInKB { get; set; }
        public string Location { get; set; }
    }
}
